#!/usr/bin/env bash
# Print a privacy-safe token/cost summary for an OpenCode SQLite session.
# Usage: opencode-session-debug.sh [session-id] [database]
set -euo pipefail

for command in sqlite3 jq awk; do
  command -v "$command" >/dev/null 2>&1 || {
    printf 'Error: required command not found: %s\n' "$command" >&2
    exit 1
  }
done

if (( $# > 2 )); then
  printf 'Usage: %s [session-id] [database]\n' "$0" >&2
  exit 1
fi

DATABASE=${2:-${OPENCODE_DB_PATH:-$HOME/.local/share/opencode/opencode.db}}
if [[ ! -f "$DATABASE" ]]; then
  printf 'Error: OpenCode database not found: %s\n' "$DATABASE" >&2
  exit 1
fi

SESSION=${1:-$(sqlite3 "$DATABASE" \
  'SELECT id FROM session WHERE parent_id IS NULL ORDER BY time_updated DESC, id DESC LIMIT 1')}
if [[ -z "$SESSION" ]]; then
  printf 'Error: no OpenCode session found in %s\n' "$DATABASE" >&2
  exit 1
fi

# Session IDs are generated by OpenCode, but quote defensively for SQLite.
SESSION_SQL=${SESSION//\'/\'\'}
SESSION_JSON=$(sqlite3 -json "$DATABASE" \
  "SELECT id, title FROM session WHERE id = '$SESSION_SQL' LIMIT 1")
if [[ $(jq 'length' <<<"$SESSION_JSON") -eq 0 ]]; then
  printf 'Error: session not found: %s\n' "$SESSION" >&2
  exit 1
fi

MESSAGES=$(sqlite3 -json "$DATABASE" \
  "SELECT id, time_created, data FROM message WHERE session_id = '$SESSION_SQL' ORDER BY time_created, id")
PARTS=$(sqlite3 -json "$DATABASE" \
  "SELECT message_id, data FROM part WHERE session_id = '$SESSION_SQL' ORDER BY time_created, id")

TITLE=$(jq -r '.[0].title' <<<"$SESSION_JSON")
MODELS=$(jq -r \
  '[.[] | .data | fromjson? | select(.role == "assistant") | .modelID // empty] | unique | join(", ") | if . == "" then "unknown" else . end' \
  <<<"$MESSAGES")
REPORTED=$(jq -r \
  '[.[] | .data | fromjson? | select(.role == "assistant") | .cost // 0] | add // 0' \
  <<<"$MESSAGES")

printf 'Session: %s\n' "$SESSION"
printf 'Title:   %s\n' "$TITLE"
printf 'DB:      %s\n' "$DATABASE"
printf 'Models:  %s\n' "$MODELS"
printf 'Cost:    $%.6f reported\n\n' "$REPORTED"

jq -nr --argjson messages "$MESSAGES" --argjson parts "$PARTS" '
  ($parts | reduce .[] as $row ({};
    ($row.data | fromjson?) as $part |
    if $part.type == "file" and ($part.mime // "" | startswith("image/"))
    then .[$row.message_id] = ((.[$row.message_id] // 0) + 1)
    else . end
  )) as $images |
  (reduce $messages[] as $row (
    {turn: 0, call: 0, pending_images: 0, rows: []};
    ($row.data | fromjson?) as $message |
    if $message.role == "user" then
      .turn += 1 | .call = 0 | .pending_images = ($images[$row.id] // 0)
    elif $message.role == "assistant" and $message.tokens != null and .turn > 0 then
      ($message.tokens.input // 0) as $input |
      ($message.tokens.cache.read // 0) as $read |
      ($message.tokens.cache.write // 0) as $write |
      ($message.tokens.output // 0) as $output |
      ($message.tokens.reasoning // 0) as $reasoning |
      ($message.cost // 0) as $cost |
      if ($input + $read + $write + $output + $reasoning + $cost) > 0 then
        .call += 1 |
        .rows += [[.turn, .call, ($message.providerID // "unknown"),
          ($message.modelID // "unknown"), .pending_images, $input, $read,
          $write, $output, $reasoning, $cost]] |
        .pending_images = 0
      else . end
    else . end
  ) | .rows) as $raw |
  ($raw | map(.[0]) | unique) as $turns |
  ($raw | map(. as $row | .[0] = (($turns | index($row[0])) + 1))) |
  reduce .[] as $row ({previous: null, output: []};
    ($row[2]) as $provider | ($row[3]) as $model |
    ($row[6]) as $read |
    (if .previous == null then ["baseline", null, null]
     elif .previous.provider != $provider or .previous.model != $model then ["not-comparable", null, null]
     else (.previous.read + (if .previous.write > 0 then .previous.write elif .previous.provider == "openai" then .previous.input else 0 end)) as $prior |
       if $prior == 0 then ["not-comparable", null, null]
       else ($read / $prior) as $retained |
         [(if $retained >= 0.9 then "hit" elif $retained <= 0.1 then "full-miss" else "partial-hit" end), $prior, $retained]
       end
     end) as $cache |
    .output += [$row + $cache] |
    .previous = {provider: $provider, model: $model, input: $row[5], read: $read, write: $row[7]}
  ) | .output[] | @tsv
' | awk -F '\t' '
  BEGIN {
    printf "%-5s %-18s %3s %9s %9s %9s %7s %7s %9s %9s %8s %8s %11s %-14s\n",
      "T.C", "MODEL", "IMG", "NEW", "READ", "WRITE", "CACHED", "RETAIN",
      "PREV", "LOST", "OUT", "RSN", "REPORTED", "CACHE"
  }
  {
    model = $4
    if (length(model) > 18) model = substr(model, 1, 17) "~"
    total = $6 + $7 + $8
    cached = total == 0 ? "-" : sprintf("%.1f%%", 100 * $7 / total)
    retain = $14 == "" ? "-" : sprintf("%.1f%%", 100 * $14)
    prior = $13 == "" ? "-" : sprintf("%d", $13)
    lost = $13 == "" ? "-" : sprintf("%d", ($13 > $7 ? $13 - $7 : 0))
    printf "%-5s %-18s %3s %9d %9d %9d %7s %7s %9s %9s %8d %8d $%10.6f %-14s\n",
      $1 "." $2, model, ($5 == 0 ? "-" : "Y"), $6, $7, $8, cached,
      retain, prior, lost, $9, $10, $11, $12
  }
'
